project:
  type: website

website:
  title: "Urban morphometrics | EuroFab"
  sidebar:
    tools:
    - icon: github
      href: https://github.com/eurofab-project/morphometrics
    contents:
    - section: "About"
      contents:
      - text: Project homepage
        href:  https://eurofab-project.github.io/
      - text: Technical Notes
        href:  https://eurofab-project.github.io/technical-notes/
      - text: Talks
        href:  https://eurofab-project.github.io/talks/
      - text: Data product
        href:  https://eurofab.org/data.html
      - section: "Other work streams"
        contents:
        - text: Earth observation
          href:  https://eurofab-project.github.io/eo/
    - section: "Notebooks"
      contents:
      - notebooks/1_download_ms_data.ipynb
      - notebooks/1_download_ov_data.ipynb
      - notebooks/2_process_regions.ipynb
      - notebooks/3_assign_targets.ipynb
      - notebooks/4_assign_buildings_to_h3.ipynb
      - notebooks/5_train_test_split.ipynb
      - notebooks/6_single_model_training.ipynb
      - notebooks/7_figures_and_tables.ipynb
      - notebooks/interactive_exploration.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Open Sans"
    include-in-header: assets/font.html




